settings:
  showPassedChecks: true
  reportToConsole: true
  prefix: "[LaunchGuard]"
  runOnStartup: false
  startupDelayTicks: 100
  saveReports: false
  reportsToKeep: 25
  exportsToKeep: 25
  baselineReportsToKeep: 25
